repositories:
  remote:
   - https://repo1.maven.org/maven2

artifacts:
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  javax_javaee: javax:javaee-api:jar:7.0

  eclipselink: org.eclipse.persistence:eclipselink:jar:2.5.1
  h2db: com.h2database:h2:jar:1.3.159
